#!/bin/bash

# Configure Zone News Bot with Mini App via BotFather
# This script provides instructions for manual configuration

echo "🤖 Zone News Bot - Mini App Configuration Guide"
echo "=============================================="
echo ""
echo "📱 MINI APP URLs:"
echo "Main Mini App: http://67.219.107.230/miniapp.html"
echo "Admin Panel: http://67.219.107.230/admin.html"
echo ""
echo "🔧 STEPS TO CONFIGURE IN TELEGRAM:"
echo ""
echo "1. Open Telegram and go to @BotFather"
echo "2. Send: /mybots"
echo "3. Select: @ZoneNewsBot (or your bot name)"
echo "4. Click: Bot Settings"
echo "5. Click: Menu Button"
echo "6. Click: Configure menu button"
echo "7. Enter URL: http://67.219.107.230/miniapp.html"
echo "8. Enter button text: 📰 Open Zone News"
echo ""
echo "Alternative for Web App:"
echo "1. In BotFather, select your bot"
echo "2. Click: Bot Settings"
echo "3. Click: Web App"
echo "4. Enter URL: http://67.219.107.230/miniapp.html"
echo "5. Enter name: Zone News"
echo ""
echo "📝 TEST COMMANDS TO ADD:"
echo "/start - Start the bot"
echo "/news - Get latest news"
echo "/subscribe - View subscription plans"
echo "/mytier - Check your current tier"
echo "/help - Get help"
echo ""
echo "🔗 WEBHOOK CONFIGURATION:"
echo "Current webhook: https://bot.thezonenews.com/webhook"
echo ""
echo "To set webhook manually:"
echo "curl -X POST https://api.telegram.org/bot8132879580:AAFgNLe51T37LyDSl3g0-_jAsN1-k8ABfPk/setWebhook \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"url\": \"https://bot.thezonenews.com/webhook\"}'"
echo ""
echo "✅ Once configured, users can:"
echo "1. Open @ZoneNewsBot"
echo "2. Click the menu button (bottom left)"
echo "3. Access the mini app directly"
echo ""
echo "📊 Admin Access:"
echo "Admin dashboard: http://67.219.107.230/admin.html"
echo "(Add authentication before production use!)"